In [2]:
 import pandas as pd
df = pd.read_csv('SuperMarket Analysis.csv')
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [3]:
#chek the struture
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB
None

In [4]:
#check summary stats(numerical columns)
print(df.describe())

        Unit price     Quantity       Tax 5%        Sales        cogs  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.00000
mean     55.672130     5.510000    15.379369   322.966749   307.58738
std      26.494628     2.923431    11.708825   245.885335   234.17651
min      10.080000     1.000000     0.508500    10.678500    10.17000
25%      32.875000     3.000000     5.924875   124.422375   118.49750
50%      55.230000     5.000000    12.088000   253.848000   241.76000
75%      77.935000     8.000000    22.445250   471.350250   448.90500
max      99.960000    10.000000    49.650000  1042.650000   993.00000

       gross margin percentage  gross income      Rating
count             1.000000e+03   1000.000000  1000.00000
mean              4.761905e+00     15.379369     6.97270
std               6.131498e-14     11.708825     1.71858
min               4.761905e+00      0.508500     4.00000
25%               4.761905e+00      5.924875     5.50000
50%               4.761905e+00     12.088000     7.00000
75%               4.761905e+00     22.445250     8.50000
max               4.761905e+00     49.650000    10.00000

In [5]:
#check the shape(row,column)
print("shape:",df.shape)

shape: (1000, 17)

In [7]:
#chek th column names
print("column:",df.columns)

column: Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [15]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','-').str.replace('%','percent')
print(df.columns)

Index(['invoice-id', 'branch', 'city', 'customer-type', 'gender',
       'product-line', 'unit-price', 'quantity', 'tax-5percent', 'sales',
       'date', 'time', 'payment', 'cogs', 'gross-margin-percentage',
       'gross-income', 'rating'],
      dtype='object')

In [22]:
female_customers = df[df['gender'].str.lower() == 'female']
print(female_customers.head())

    invoice-id branch       city customer-type  gender  \
0  750-67-8428   Alex     Yangon        Member  Female
1  226-31-3081   Giza  Naypyitaw        Normal  Female
2  631-41-3108   Alex     Yangon        Normal  Female
3  123-19-1176   Alex     Yangon        Member  Female
4  373-73-7910   Alex     Yangon        Member  Female

             product-line  unit-price  quantity  tax-5percent     sales  \
0       Health and beauty       74.69         7       26.1415  548.9715
1  Electronic accessories       15.28         5        3.8200   80.2200
2      Home and lifestyle       46.33         7       16.2155  340.5255
3       Health and beauty       58.22         8       23.2880  489.0480
4       Sports and travel       86.31         7       30.2085  634.3785

        date         time      payment    cogs  gross-margin-percentage  \
0   1/5/2019   1:08:00 PM      Ewallet  522.83                 4.761905
1   3/8/2019  10:29:00 AM         Cash   76.40                 4.761905
2   3/3/2019   1:23:00 PM  Credit card  324.31                 4.761905
3  1/27/2019   8:33:00 PM      Ewallet  465.76                 4.761905
4   2/8/2019  10:37:00 AM      Ewallet  604.17                 4.761905

   gross-income  rating
0       26.1415     9.1
1        3.8200     9.6
2       16.2155     7.4
3       23.2880     8.4
4       30.2085     5.3

In [23]:
cash_muqablah = df[(df['payment'] == 'Cash') & (df['city'] == 'Muqablah')]
print(cash_muqablah.head())

Empty DataFrame
Columns: [invoice-id, branch, city, customer-type, gender, product-line, unit-price, quantity, tax-5percent, sales, date, time, payment, cogs, gross-margin-percentage, gross-income, rating]
Index: []

In [20]:
print(df.shape)

(1000, 17)

In [24]:
print(df['city'].unique())

['Yangon' 'Naypyitaw' 'Mandalay']

In [27]:
cash_yangon = df[(df['payment'] == 'Cash')&(df['city'] == 'Yangon')]
print(cash_yangon.head())

     invoice-id branch    city customer-type  gender        product-line  \
14  829-34-3910   Alex  Yangon        Member  Female   Health and beauty
29  848-62-7243   Alex  Yangon        Member  Female   Health and beauty
51  162-48-8011   Alex  Yangon        Member  Female  Food and beverages
56  106-35-6779   Alex  Yangon        Member  Female  Home and lifestyle
58  817-48-8732   Alex  Yangon        Member  Female  Home and lifestyle

    unit-price  quantity  tax-5percent     sales       date         time  \
14       71.38        10       35.6900  749.4900  3/29/2019   7:21:00 PM
29       24.89         9       11.2005  235.2105  3/15/2019   3:36:00 PM
51       44.59         5       11.1475  234.0975  2/10/2019   3:10:00 PM
56       44.34         2        4.4340   93.1140  3/27/2019  11:26:00 AM
58       72.35        10       36.1750  759.6750  1/20/2019   3:55:00 PM

   payment    cogs  gross-margin-percentage  gross-income  rating
14    Cash  713.80                 4.761905       35.6900     5.7
29    Cash  224.01                 4.761905       11.2005     7.4
51    Cash  222.95                 4.761905       11.1475     8.5
56    Cash   88.68                 4.761905        4.4340     5.8
58    Cash  723.50                 4.761905       36.1750     5.4

In [26]:
cash_yangon = df[(df['payment'] == 'Cash') & (df['city'] == 'Yangon')]
print(cash_yangon.head())

     invoice-id branch    city customer-type  gender        product-line  \
14  829-34-3910   Alex  Yangon        Member  Female   Health and beauty
29  848-62-7243   Alex  Yangon        Member  Female   Health and beauty
51  162-48-8011   Alex  Yangon        Member  Female  Food and beverages
56  106-35-6779   Alex  Yangon        Member  Female  Home and lifestyle
58  817-48-8732   Alex  Yangon        Member  Female  Home and lifestyle

    unit-price  quantity  tax-5percent     sales       date         time  \
14       71.38        10       35.6900  749.4900  3/29/2019   7:21:00 PM
29       24.89         9       11.2005  235.2105  3/15/2019   3:36:00 PM
51       44.59         5       11.1475  234.0975  2/10/2019   3:10:00 PM
56       44.34         2        4.4340   93.1140  3/27/2019  11:26:00 AM
58       72.35        10       36.1750  759.6750  1/20/2019   3:55:00 PM

   payment    cogs  gross-margin-percentage  gross-income  rating
14    Cash  713.80                 4.761905       35.6900     5.7
29    Cash  224.01                 4.761905       11.2005     7.4
51    Cash  222.95                 4.761905       11.1475     8.5
56    Cash   88.68                 4.761905        4.4340     5.8
58    Cash  723.50                 4.761905       36.1750     5.4

In [28]:
#case insensitive filtering using .str.lower()
#filter gender female(case-insensitive)
female_customers = df[df['gender'].str.lower() == 'female']

In [30]:
pip install pandas

Requirement already satisfied: pandas in c:\users\patil\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\patil\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\patil\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\patil\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\patil\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\patil\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [33]:
# pandas series
import pandas as pd
data = [10,20,30,40,50]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [34]:
# create series with custome index
s2 = pd.Series([100,200,300],index = ['a','b','c'])
print(s2)

a    100
b    200
c    300
dtype: int64

In [37]:
#create dataframe from dictionary
data = {
    'name' :['Alice','bob','charlie'],
    'age':[25,30,35],
    'city':['mumbai','delhi','pune']
}

df = pd.DataFrame(data)
print(df)

      name  age    city
0    Alice   25  mumbai
1      bob   30   delhi
2  charlie   35    pune

In [40]:
#creating dataframe from list a lists
students = [['raj',86],['simeran',67],['tina',95]]
df = pd.DataFrame(students,columns = ['name','marks'])
print(df)

      name  marks
0      raj     86
1  simeran     67
2     tina     95

In [41]:
# crate series from a list
marks = [45,56,78]
series = pd.Series(marks)
print(series)

0    45
1    56
2    78
dtype: int64

In [47]:
colours = ['red','pink','blue']
s=pd.Series(colours)
print(s)

0     red
1    pink
2    blue
dtype: object

In [51]:
student = [['sam',34],['maan',23],['gas',21]]
df = pd.DataFrame(student,columns=['name','age'])
print(df)

   name  age
0   sam   34
1  maan   23
2   gas   21

In [52]:
data={
    'name':{0:'sam',1:'simran'},
    'age':{0:20,1:31}
}
df = pd.DataFrame(data)
print(df)

     name  age
0     sam   20
1  simran   31

In [53]:
data = {
    'name':['raj','simaran','ham'],
    'age':[33,87,56],
    'history':['math','science','hindi']
}
dg = pd.DataFrame(data)
print(dg)

      name  age  history
0      raj   33     math
1  simaran   87  science
2      ham   56    hindi

In [57]:
# from numpy arrays
import numpy as np
import pandas as pd

In [59]:
arr = np.array([[1,2],[2,4],[4,6]])
df= pd.DataFrame(arr,columns =['col1','col2'])
print(df)

   col1  col2
0     1     2
1     2     4
2     4     6

In [67]:
data = ['Apple','Banana','cherry','mango','orange']
s= pd.Series(data,index=['A','B','C','D','E'])
print(s)

A     Apple
B    Banana
C    cherry
D     mango
E    orange
dtype: object

In [71]:
fruits =pd.Series(['Apple','Banana','cherry','mango','orange'],index=['A','B','C','D','E'])
print(fruits)

A     Apple
B    Banana
C    cherry
D     mango
E    orange
dtype: object

In [72]:
# create a dataframe from this dictionry
data = {
    'product':['pen','pencile','ntebook'],
    'price':[10,20,30],
    'stock':[100,200,150]
}
s2 = pd.DataFrame(data)
print(s2)

   product  price  stock
0      pen     10    100
1  pencile     20    200
2  ntebook     30    150

In [4]:
#create a 3*3 dataframe from numpy arry
import numpy as np
import pandas as pd
arry = np.arange(1,10).reshape(3,3)
df= pd.DataFrame(arry,columns= ['col1','col2','col3'])
print(df)

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [5]:
data = {
    'name':['Aman', 'neha', 'Tina'],
     'Age' :[22,25,24],
     'city':['mumbai','delhi','pune']
}
df = pd.DataFrame(data)
print(df)

   name  Age    city
0  Aman   22  mumbai
1  neha   25   delhi
2  Tina   24    pune

In [6]:
print(df['name'])

0    Aman
1    neha
2    Tina
Name: name, dtype: object

In [7]:
print(df[['name','city']])

   name    city
0  Aman  mumbai
1  neha   delhi
2  Tina    pune

In [8]:
 print(df[['Age','city','name']])

   Age    city  name
0   22  mumbai  Aman
1   25   delhi  neha
2   24    pune  Tina

In [9]:
# Accesing the row
#df.loc[] uses labels (index names)
#df.iloc[] uses position numbers(like index o,1,2)
print(df.loc[2])

name    Tina
Age       24
city    pune
Name: 2, dtype: object

In [10]:
print(df.loc[[0,2]])

   name  Age    city
0  Aman   22  mumbai
2  Tina   24    pune

In [11]:
#using df.iloc[](position based)
#get the row first
print(df.iloc[0])

name      Aman
Age         22
city    mumbai
Name: 0, dtype: object

In [13]:
# get the first row
print(df.iloc[0:3])

   name  Age    city
0  Aman   22  mumbai
1  neha   25   delhi
2  Tina   24    pune

In [14]:
# single cell using loc [row_label,column_name]
print(df.loc[1,'city'])

delhi

In [16]:
print(df.loc[0,'Age'])

22

In [17]:
# single cell iloc[row_index,column_index]
#print(df.iloc[2,0])
print(df.iloc[1,2])

delhi

In [19]:
 import pandas as pd
data = {
    'name':['Amit','Sneha','Raj','Priya'],
    'Age':[21,22,23,26],
    'city':['pune','mumbai','delhi','bengaluru'],
    'marks':[88,76,90,85]
}
df = pd.DataFrame(data)
print(df)

    name  Age       city  marks
0   Amit   21       pune     88
1  Sneha   22     mumbai     76
2    Raj   23      delhi     90
3  Priya   26  bengaluru     85

In [22]:
 print(df['city'])

0         pune
1       mumbai
2        delhi
3    bengaluru
Name: city, dtype: object

In [23]:
print(df[['name','marks']])

    name  marks
0   Amit     88
1  Sneha     76
2    Raj     90
3  Priya     85

In [26]:
print(df.loc[3])

name         Priya
Age             26
city     bengaluru
marks           85
Name: 3, dtype: object

In [25]:
print(df.iloc[3])

name         Priya
Age             26
city     bengaluru
marks           85
Name: 3, dtype: object

In [30]:
print(df.loc[3,'marks'])

85

In [31]:
print(df.iloc[3,3])

85

In [32]:
print(df.shape)

(4, 4)

In [34]:
print(df.columns)

Index(['name', 'Age', 'city', 'marks'], dtype='object')

In [35]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [36]:
import pandas as pd

data1 = {
    'Name': ['Amit', 'Sneha', 'Raj', 'Priya', 'Neha'],
    'Age': [21, 22, 23, 22, 25],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Pune'],
    'Marks': [88, 76, 90, 85, 60]
}

df1 = pd.DataFrame(data1)
print(df1)

    Name  Age       City  Marks
0   Amit   21       Pune     88
1  Sneha   22     Mumbai     76
2    Raj   23      Delhi     90
3  Priya   22  Bangalore     85
4   Neha   25       Pune     60

In [37]:
print(df[df['marks']>80])

    name  Age       city  marks
0   Amit   21       pune     88
2    Raj   23      delhi     90
3  Priya   26  bengaluru     85

In [39]:
print(df[df['city'] == 'pune'])

   name  Age  city  marks
0  Amit   21  pune     88

In [40]:
print(df[df['Age'] >20 ])

    name  Age       city  marks
0   Amit   21       pune     88
1  Sneha   22     mumbai     76
2    Raj   23      delhi     90
3  Priya   26  bengaluru     85

In [41]:
print(df[(df['marks']>80) &(df['city'] == 'pune')])

   name  Age  city  marks
0  Amit   21  pune     88

In [42]:
print(df[df['marks']>80 | (df['city'] == 'pune')])

    name  Age       city  marks
0   Amit   21       pune     88
1  Sneha   22     mumbai     76
2    Raj   23      delhi     90
3  Priya   26  bengaluru     85

In [43]:
 #using ,isin()
#get sudents from pune or delhi
print(df[df['city'].isin(['pune','delhi'])])

   name  Age   city  marks
0  Amit   21   pune     88
2   Raj   23  delhi     90

In [44]:
# get students whise names as in list
print(df[df['name'].isin(['Amit','priya'])])

   name  Age  city  marks
0  Amit   21  pune     88

In [45]:
import pandas as pd

data = {
    'Name': ['Amit', 'Sneha', 'Raj', 'Priya', 'Neha', 'Vikas'],
    'Age': [21, 22, 23, 22, 25, 24],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Pune', 'Delhi'],
    'Marks': [88, 76, 90, 85, 60, 92]
}

df = pd.DataFrame(data)
print(df)

    Name  Age       City  Marks
0   Amit   21       Pune     88
1  Sneha   22     Mumbai     76
2    Raj   23      Delhi     90
3  Priya   22  Bangalore     85
4   Neha   25       Pune     60
5  Vikas   24      Delhi     92

In [47]:
print(df[df['Marks'] > 85])

    Name  Age   City  Marks
0   Amit   21   Pune     88
2    Raj   23  Delhi     90
5  Vikas   24  Delhi     92

In [48]:
print(df[df['City'].isin(['Pune','Delhi'])])

    Name  Age   City  Marks
0   Amit   21   Pune     88
2    Raj   23  Delhi     90
4   Neha   25   Pune     60
5  Vikas   24  Delhi     92

In [49]:
print(df[(df['Age'] ==22)&(df['City']=='Mumbai')])

    Name  Age    City  Marks
1  Sneha   22  Mumbai     76

In [50]:
print(df[df['Marks'].between(80,90)])

    Name  Age       City  Marks
0   Amit   21       Pune     88
2    Raj   23      Delhi     90
3  Priya   22  Bangalore     85

In [51]:
print(df.query("City =='Delhi' | Age >24"))

    Name  Age   City  Marks
2    Raj   23  Delhi     90
4   Neha   25   Pune     60
5  Vikas   24  Delhi     92

In [52]:
#Find missing value
print(df.isnull())

    Name    Age   City  Marks
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False

In [53]:
#count missing values per column
print(df.isnull().sum())

Name     0
Age      0
City     0
Marks    0
dtype: int64

In [76]:
  #Drop rows with any missing  values
df_cleaned = df.dropna()
print(df_cleaned)

    Name  Age       City  Score  marks
0   Amit   21       Pune     88     88
1  Sneha   22     Mumbai     76     76
2    Raj   23      Delhi     90     90
3  Priya   22  Bangalore     85     85
4   Neha   25       Pune     60     60
5  Vikas   24      Delhi     92     92

In [57]:
# fill missing values with spacific value
df_filled = df.fillna(0)
print(df_filled)

    Name  Age       City  Marks
0   Amit   21       Pune     88
1  Sneha   22     Mumbai     76
2    Raj   23      Delhi     90
3  Priya   22  Bangalore     85
4   Neha   25       Pune     60
5  Vikas   24      Delhi     92

In [73]:
df['marks'] = df['marks'].fillna(df['marks'].mean())
print(df['marks'])

0    88
1    76
2    90
3    85
4    60
5    92
Name: marks, dtype: int64

In [67]:
df = df.rename(columns = {'Marks':'Score'})
print(df)

    Name  Age       City  Score  marks
0   Amit   21       Pune     88     88
1  Sneha   22     Mumbai     76     76
2    Raj   23      Delhi     90     90
3  Priya   22  Bangalore     85     85
4   Neha   25       Pune     60     60
5  Vikas   24      Delhi     92     92

In [77]:
df.columns = ['StudentName', 'StudentAge', 'City', 'Score','marks']
print(df.columns)

Index(['StudentName', 'StudentAge', 'City', 'Score', 'marks'], dtype='object')

In [82]:
df = df.drop(columns =['Score'])
print(df)

  StudentName  StudentAge
0        Amit          21
1       Sneha          22
2         Raj          23
3       Priya          22
4        Neha          25
5       Vikas          24

In [96]:
 # Applying Functions & Data Transformations in Pandas
import pandas as pd

data = {
    'Name': ['Amit', 'Sneha', 'Raj', 'Priya'],
    'Marks': [88, 76, 90, 85],
    'Grade': ['B', 'C', 'A', 'B']
}

df = pd.DataFrame(data)
print(df)

    Name  Marks Grade
0   Amit     88     B
1  Sneha     76     C
2    Raj     90     A
3  Priya     85     B

In [97]:
#apply a function to each row or column
#convert marks to percentage of 100
df['marks'] = df['Marks'].apply(lambda x: x/100)
print(df['marks'])

0    0.88
1    0.76
2    0.90
3    0.85
Name: marks, dtype: float64

In [98]:
# round the percentage to 2 decimal places
df['Marks'] = df['marks'].apply(lambda x : round(x,2))
print(df['Marks'])

0    0.88
1    0.76
2    0.90
3    0.85
Name: Marks, dtype: float64

In [102]:
# converts grades to remarks
df['Remarks'] = df['Grade'].map({'A': 'Excellent', 'B':'Good',  'C': 'Average'})
print(df['Remarks'])

0         Good
1      Average
2    Excellent
3         Good
Name: Remarks, dtype: object

In [105]:
df['Remarks'] = df['Grade'].map({'A': 'Excellent', 'B': 'Good', 'C': 'Average'})
print(df['Remarks'])

0         Good
1      Average
2    Excellent
3         Good
Name: Remarks, dtype: object

In [106]:
df['name'] = df['Name'].replace('Amit','Aman')
print(df['name'])

0     Aman
1    Sneha
2      Raj
3    Priya
Name: name, dtype: object

In [107]:
df['grade'] = df['Grade'].replace({'A': '1st', 'B': '2nd', 'C':  '3rd'})
print(df['grade'])

0    2nd
1    3rd
2    1st
3    2nd
Name: grade, dtype: object

In [108]:
df['marks']= df['Marks'].apply(lambda X: X * 100)
print(df['marks'])

0    88.0
1    76.0
2    90.0
3    85.0
Name: marks, dtype: float64

In [109]:
import pandas as pd

data = {
    'Name': ['Amit', 'Sneha', 'Raj', 'Priya'],
    'Marks': [88, 76, 90, 85],
    'Grade': ['B', 'C', 'A', 'B']
}

df = pd.DataFrame(data)
print(df)

    Name  Marks Grade
0   Amit     88     B
1  Sneha     76     C
2    Raj     90     A
3  Priya     85     B

In [111]:
df['marks'] = df['Marks'].apply(lambda x : x +5)
print(df['marks'])

0    93
1    81
2    95
3    90
Name: marks, dtype: int64

In [112]:
#use .map() to convert grades to remark
df['Remarks'] = df['Grade'].map({'A': 'Excellent' , 'B': 'Good', 'C': 'Average'})
print(df['Remarks'])

0         Good
1      Average
2    Excellent
3         Good
Name: Remarks, dtype: object

In [113]:
#use replace
df['name'] = df['Name'].replace('Amit','Aman')
print(df['name'])

0     Aman
1    Sneha
2      Raj
3    Priya
Name: name, dtype: object

In [114]:
df['result'] = df['Marks'].apply(
    lambda x : 'distinction' if x >= 90 else ('passed' if x >= 80 else 'needs improvement'))

In [115]:
print(df['result'])

0               passed
1    needs improvement
2          distinction
3               passed
Name: result, dtype: object

In [116]:
print(df)

    Name  Marks Grade  marks    Remarks   name             result
0   Amit     88     B     93       Good   Aman             passed
1  Sneha     76     C     81    Average  Sneha  needs improvement
2    Raj     90     A     95  Excellent    Raj        distinction
3  Priya     85     B     90       Good  Priya             passed

In [117]:
import pandas as pd

data = {
    'Name': ['Amit', 'Sneha', 'Raj', 'Priya'],
    'Marks': [88, 76, 90, 85],
    'Grade': ['B', 'C', 'A', 'B']
}

df = pd.DataFrame(data)

# Replace name
df['Name'] = df['Name'].replace('Amit', 'Aman')

# Add bonus
df['Marks'] = df['Marks'].apply(lambda x: x + 5)

# Grade to remarks
df['Remarks'] = df['Grade'].map({'A': 'Excellent', 'B': 'Good', 'C': 'Average'})

# Result based on updated Marks
df['Result'] = df['Marks'].apply(
    lambda x: 'distinction' if x >= 90 else ('passed' if x >= 80 else 'needs improvement')
)

print(df)

    Name  Marks Grade    Remarks       Result
0   Aman     93     B       Good  distinction
1  Sneha     81     C    Average       passed
2    Raj     95     A  Excellent  distinction
3  Priya     90     B       Good  distinction

In [118]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Employee': ['Amit', 'Sneha', 'Raj', 'Priya', 'Neha', 'Vikas'],
    'Salary': [50000, 52000, 45000, 47000, 60000, 61000],
    'Age': [25, 27, 24, 26, 28, 30]
}

df = pd.DataFrame(data)
print(df)

  Department Employee  Salary  Age
0      Sales     Amit   50000   25
1      Sales    Sneha   52000   27
2         HR      Raj   45000   24
3         HR    Priya   47000   26
4         IT     Neha   60000   28
5         IT    Vikas   61000   30

In [122]:
df_sorted = df.sort_values(by = 'Salary')
print(df_sorted)

  Department Employee  Salary  Age
2         HR      Raj   45000   24
3         HR    Priya   47000   26
0      Sales     Amit   50000   25
1      Sales    Sneha   52000   27
4         IT     Neha   60000   28
5         IT    Vikas   61000   30

In [123]:
df_sorted = df.sort_values(by = 'Salary', ascending = False)
print(df_sorted)

  Department Employee  Salary  Age
5         IT    Vikas   61000   30
4         IT     Neha   60000   28
1      Sales    Sneha   52000   27
0      Sales     Amit   50000   25
3         HR    Priya   47000   26
2         HR      Raj   45000   24

In [124]:
df_sorted = df.sort_values(by = ['Department' , 'Salary'])
print(df_sorted)

  Department Employee  Salary  Age
2         HR      Raj   45000   24
3         HR    Priya   47000   26
4         IT     Neha   60000   28
5         IT    Vikas   61000   30
0      Sales     Amit   50000   25
1      Sales    Sneha   52000   27

In [125]:
df_groupby = df.groupby('Department')['Salary'].sum()
print(df_groupby)

Department
HR        92000
IT       121000
Sales    102000
Name: Salary, dtype: int64

In [126]:
df.groupby('Department')['Age'].mean()

Department
HR       25.0
IT       29.0
Sales    26.0
Name: Age, dtype: float64

In [127]:
df.groupby('Department')['Employee'].count()

Department
HR       2
IT       2
Sales    2
Name: Employee, dtype: int64

In [129]:
df.groupby('Department')['Salary' ].agg(['sum','mean'])

               sum     mean
Department
HR           92000  46000.0
IT          121000  60500.0
Sales       102000  51000.0

In [130]:
df.groupby('Department').agg({
    'Salary': 'mean',
    'Age': 'max'
})

             Salary  Age
Department
HR          46000.0   26
IT          60500.0   30
Sales       51000.0   27

In [131]:
df.groupby('Department')['Salary'].sum().reset_index()

  Department  Salary
0         HR   92000
1         IT  121000
2      Sales  102000

In [132]:
df

  Department Employee  Salary  Age
0      Sales     Amit   50000   25
1      Sales    Sneha   52000   27
2         HR      Raj   45000   24
3         HR    Priya   47000   26
4         IT     Neha   60000   28
5         IT    Vikas   61000   30

In [133]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT', 'Sales', 'HR', 'IT'],
    'Employee': ['Amit', 'Sneha', 'Raj', 'Priya', 'Neha', 'Vikas', 'Karan', 'Divya', 'Meena'],
    'Salary': [50000, 52000, 45000, 47000, 60000, 61000, 53000, 48000, 59000],
    'Age': [25, 27, 24, 26, 28, 30, 29, 23, 31]
}

df = pd.DataFrame(data)
print(df)

  Department Employee  Salary  Age
0      Sales     Amit   50000   25
1      Sales    Sneha   52000   27
2         HR      Raj   45000   24
3         HR    Priya   47000   26
4         IT     Neha   60000   28
5         IT    Vikas   61000   30
6      Sales    Karan   53000   29
7         HR    Divya   48000   23
8         IT    Meena   59000   31

In [137]:
#df_sorted = df.sort_values(by = 'Salary')
#print(df_sorted)

#df_sorted = df.sort_values(by = 'Age',ascending = True)
#print(df_sorted)

df.groupby('Department')['Salary'].sum()

Department
HR       140000
IT       180000
Sales    155000
Name: Salary, dtype: int64

In [146]:
df.groupby('Department')['Age'].mean()

Department
HR       24.333333
IT       29.666667
Sales    27.000000
Name: Age, dtype: float64

In [145]:
df.groupby('Department')['Salary'].agg(['sum', 'mean'])

               sum          mean
Department
HR          140000  46666.666667
IT          180000  60000.000000
Sales       155000  51666.666667

In [147]:
df.loc[df.groupby('Department')['Age'].idxmin()]

  Department Employee  Salary  Age
7         HR    Divya   48000   23
4         IT     Neha   60000   28
0      Sales     Amit   50000   25

In [143]:
df.groupby('Department')['Employee'].count()

Department
HR       3
IT       3
Sales    3
Name: Employee, dtype: int64

In [148]:
import pandas as pd

data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT', 'Sales', 'HR', 'IT'],
    'Employee': ['Amit', 'Sneha', 'Raj', 'Priya', 'Neha', 'Vikas', 'Karan', 'Divya', 'Meena'],
    'Salary': [50000, 52000, 45000, 47000, 60000, 61000, 53000, 48000, 59000],
    'Age': [25, 27, 24, 26, 28, 30, 29, 23, 31]
}

df = pd.DataFrame(data)

In [149]:
salary_dept = df.groupby('Department')['Salary'].sum().sort_values(ascending = False)
print(salary_dept)

Department
IT       180000
Sales    155000
HR       140000
Name: Salary, dtype: int64

In [151]:
df.groupby('Department').agg({
    'Age':'mean',
    'Salary':'mean'
})

                  Age        Salary
Department
HR          24.333333  46666.666667
IT          29.666667  60000.000000
Sales       27.000000  51666.666667

In [155]:
high_salary = df.loc[df['Salary'].idxmax()]
print(high_salary)

Department       IT
Employee      Vikas
Salary        61000
Age              30
Name: 5, dtype: object

In [160]:
def Salary_Level(s):
    if s >= 58000:
        return 'high'
    elif s >= 50000:
        return 'medium'
    else:
        return 'low'

df['Salary_Level'] = df['Salary'].apply(Salary_Level)
print(df[['Employee', 'Salary', 'Salary_Level']])

  Employee  Salary Salary_Level
0     Amit   50000       medium
1    Sneha   52000       medium
2      Raj   45000          low
3    Priya   47000          low
4     Neha   60000         high
5    Vikas   61000         high
6    Karan   53000       medium
7    Divya   48000          low
8    Meena   59000         high

In [164]:
count = df['Salary_Level'].value_counts()
print(count)

Salary_Level
medium    3
low       3
high      3
Name: count, dtype: int64

youngest = df.loc[df.groupby('Department')['Age'].idxmin()]
oldest = df.loc[df.groupby('Department')['Age'].idxmax()]

print("Youngest in each department:\n", youngest[['Department', 'Employee', 'Age']])
print("Oldest in each department:\n", oldest[['Department', 'Employee', 'Age']])

In [166]:
sorted_df = df.sort_values(by=['Department', 'Salary'], ascending=[True, False])
print(sorted_df)

  Department Employee  Salary  Age Salary_level Salary_Level
7         HR    Divya   48000   23          low          low
3         HR    Priya   47000   26          low          low
2         HR      Raj   45000   24          low          low
5         IT    Vikas   61000   30         high         high
4         IT     Neha   60000   28         high         high
8         IT    Meena   59000   31         high         high
6      Sales    Karan   53000   29       medium       medium
1      Sales    Sneha   52000   27       medium       medium
0      Sales     Amit   50000   25       medium       medium

In [167]:
df.to_csv('employee_dashboard.csv', index=False)

In [ ]:
Build visualizations for this project (bar plots, pie charts)?

In [2]:
import pandas as pd

# Employee Info
df1 = pd.DataFrame({
    'Emp_ID': [101, 102, 103],
    'Name': ['Amit', 'Sneha', 'Raj'],
    'Department': ['HR', 'Sales', 'IT']
})

# Employee Salary Info
df2 = pd.DataFrame({
    'Emp_ID': [101, 102, 104],
    'Salary': [50000, 52000, 55000]
})

print(df1)
print(df2)

   Emp_ID   Name Department
0     101   Amit         HR
1     102  Sneha      Sales
2     103    Raj         IT
   Emp_ID  Salary
0     101   50000
1     102   52000
2     104   55000

In [3]:
result =  pd.concat([df1,df2])
print(result)

   Emp_ID   Name Department   Salary
0     101   Amit         HR      NaN
1     102  Sneha      Sales      NaN
2     103    Raj         IT      NaN
0     101    NaN        NaN  50000.0
1     102    NaN        NaN  52000.0
2     104    NaN        NaN  55000.0

In [9]:
result1 = pd.concat([df1, df2], axis=1)
print(result1)

   Emp_ID   Name Department  Emp_ID  Salary
0     101   Amit         HR     101   50000
1     102  Sneha      Sales     102   52000
2     103    Raj         IT     104   55000

In [11]:
merged_inner = pd.merge(df1,df2 ,on = 'Emp_ID',how = 'inner')
print(merged_inner)

   Emp_ID   Name Department  Salary
0     101   Amit         HR   50000
1     102  Sneha      Sales   52000

In [14]:
merged_left = pd.merge(df1,df2 ,on = 'Emp_ID',how = 'left')
print(merged_left)

   Emp_ID   Name Department   Salary
0     101   Amit         HR  50000.0
1     102  Sneha      Sales  52000.0
2     103    Raj         IT      NaN

In [16]:
merged_right= pd.merge(df1 ,df2,on='Emp_ID',how = 'right')
print(merged_right)

   Emp_ID   Name Department  Salary
0     101   Amit         HR   50000
1     102  Sneha      Sales   52000
2     104    NaN        NaN   55000

In [17]:
merged_outer = pd.merge(df1,df2,on='Emp_ID',how='outer')
print(merged_outer)

   Emp_ID   Name Department   Salary
0     101   Amit         HR  50000.0
1     102  Sneha      Sales  52000.0
2     103    Raj         IT      NaN
3     104    NaN        NaN  55000.0

In [19]:
df1_indexed = df1.set_index('Emp_ID')
df2_indexed = df2.set_index('Emp_ID')

joined = df1_indexed.join(df2_indexed,how='inner')
print(joined)

         Name Department  Salary
Emp_ID
101      Amit         HR   50000
102     Sneha      Sales   52000

In [21]:
#summarise data like pivot table
import pandas as pd
data = {
    'Product': ['A', 'A', 'B', 'B', 'A'],
    'Region': ['East', 'West', 'East', 'West', 'East'],
    'Sales': [100, 150, 200, 130, 180]
}

df = pd.DataFrame(data)

In [22]:
df

  Product Region  Sales
0       A   East    100
1       A   West    150
2       B   East    200
3       B   West    130
4       A   East    180

In [23]:
# total sales per product and region
table =  pd.pivot_table(df,values = 'Sales',index = 'Product',columns = 'Region',aggfunc='sum')
print(table)

Region   East  West
Product
A         280   150
B         200   130

In [24]:
count = pd.crosstab(df['Product'],df['Region'])
print(count)

Region   East  West
Product
A           2     1
B           1     1